load_system(':file');
disp('success1');
posModel = get_param(":system/Subsystem", 'Position');
add_block('simulink/Ports & Subsystems/Model', ':system/Model');
disp('success2');
delete_line(':system', 'Subsystem/1', ':outBlock/1');
delete_line(':system', ':inBlock/1', 'Subsystem/1');
delete_block(':system/Subsystem');
disp('success2');
set_param(':system/Model', 'Position', posModel);
disp('success2');
load_system(':solution');
set_param(':system/Model', 'ModelFile', ':nameSolutionSystem');
disp('success4');
add_line(':system', ':inBlock/1', 'Model/1', 'autorouting', 'on');
disp('success5');
add_line(':system', 'Model/1', ':outBlock/1', 'autorouting', 'on');
disp('success6');
print('-s:system', '-djpeg', ':image');
disp('success7');
set(0,'ShowHiddenHandles','On');
set(gcf,'Units','centimeters','PaperUnits','centimeters');
disp('success8.1');
pos = get(gcf,'Position');
set(gcf,'PaperPosition',[0 0 pos(3) pos(4)],'Papersize',[ pos(3),pos(4) ]);
disp('success8.2');
set(gcf,'InvertHardcopy','off','Renderer','painters');
sim(':system', 100);
saveas(gcf, ':plotImage');
close_system(':system', 0);
data = yout.get(1);
diary :log;
disp(stepinfo(data.Values.Data, data.Values.Time));
diary off;
exit;